
import java.util.*;

public class NumberGuessing {

    public static void main(String[] args) {
        try (Scanner sc = new Scanner(System.in)) {
            int round = 0;
            System.out.println("Welcome to the Number Guessing Game");
            System.out.println("Rules of the game:");
            System.out.println("1. You have to guess the random number generated by the computer.");
            System.out.println("2. You will have a maximum of 10 attempts.");
            System.out.println("3. Your score will be equal to the number of attempts you tried to guess the number minus total attempts");
            System.out.println("4. Only integer values from 1 to 100 are allowed.");

            while (true) {
                System.out.println("\nWelcome to round " + ++round);
                System.out.println("Press 1 to start and 0 to exit");
                int choice = sc.nextInt();
                if (choice == 0) {
                    System.out.println("Thank you for visiting!");
                    return;
                }

                Random rand = new Random();
                int randomNumber = (int)(rand.nextInt(100) + 1);
                int attempts = 0;
                int maxAttempts = 10;
                int score = 0;

                while (attempts < maxAttempts) {
                    System.out.println("Enter your guess:");
                    int guess = sc.nextInt();
                    attempts++;

                    if (guess == randomNumber) {
                        System.out.println("Congrats! You guessed the number.");
                        score = maxAttempts-attempts;
                        
                        break;
                    } else if (guess > randomNumber) {
                        System.out.println("Your guess is too high.");
                    } else {
                        System.out.println("Your guess is too low.");
                    }

            }
            if (attempts==10) {
                score = maxAttempts-attempts;
                System.out.println("Sorry, you've used all attempts. The number was " + randomNumber);
            }

                System.out.println("Thank you for playing round " + round);
                System.out.println("Your score for this round is " + score);
                System.out.println("You made " + attempts + " attempts.");
                System.out.println("Press 1 to play again and 0 to exit");
                choice = sc.nextInt();

                if (choice == 0) {
                    System.out.println("Thank you for playing!");
                    break;
                }
            }

            sc.close();
        }
    }
}
